const NetworkDetails = [
    {
      txnType: 0,
      networkName: 'BNB Smart Chain',
      rpc: 'https://bsc-dataseed1.binance.org',
      chainId: 56,
      sym: 'BNB',
      explore: 'https://bscscan.com/',
    },
    {
      txnType: 2,
      networkName: 'Ethereum Mainnet',
      rpc: 'https://rpc.ankr.com/eth',
      chainId: 1,
      sym: 'ETH',
      explore: 'https://etherscan.io/',
    },
    {
      txnType: 2,
      networkName: 'PulseChain Testnet',
      rpc: 'https://rpc.v2b.testnet.pulsechain.com',
      chainId: 941,
      sym: 'PLS',
      explore: 'https://scan.v2b.testnet.pulsechain.com/',
    },
    {
      txnType: 2,
      networkName: 'Polygon Mainnet',
      rpc: 'https://polygon-rpc.com',
      chainId: 137,
      sym: 'MATIC',
      explore: 'https://polygonscan.com/',
    },
    {
      txnType: 2,
      networkName: 'Avalanche Mainnet C-Chain',
      rpc: 'https://api.avax.network/ext/bc/C/rpc',
      chainId: 43114,
      sym: 'AVAX',
      explore: 'https://snowtrace.io/',
    },
    {
      txnType: 2,
      networkName: 'Fantom Opera',
      rpc: 'https://rpc.ankr.com/fantom',
      chainId: 250,
      sym: 'FTM',
      explore: 'https://ftmscan.com/',
    },
    {
      txnType: 2,
      networkName: 'Arbitrum One',
      rpc: 'https://rpc.ankr.com/arbitrum',
      chainId: 42161,
      sym: 'ETH',
      explore: 'https://arbiscan.io/',
    },
    {
      txnType: 2,
      networkName: 'Gnosis Chain (xDAI)',
      rpc: 'https://rpc.ankr.com/gnosis',
      chainId: 100,
      sym: 'xDAI',
      explore: 'https://gnosisscan.io/',
    },
    {
      txnType: 2,
      networkName: 'Cronos Chain',
      rpc: 'https://evm.cronos.org',
      chainId: 25,
      sym: 'CRO',
      explore: 'https://cronoscan.com/',
    },
    {
      txnType: 0,
      networkName: 'Optimism',
      rpc: 'https://rpc.ankr.com/optimism',
      chainId: 10,
      sym: 'ETH',
      explore: 'https://optimistic.etherscan.io/',
    },
  ];
  
  export { NetworkDetails };
  